spring:
  application:
    name: MindVault
  main:
    allow-circular-references: true
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/mindvault}
      database: mindvault
      auto-index-creation: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}

weather:
  api:
    key: ${WEATHER_API_KEY:81332d4bfbcee71f685ba042128174c0}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
